import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import ThemeProvider from "@/providers/themeProvider";
import { cn } from "@/utils/tailwind";
import TranslationProvider from "@/providers/translationProvider";

const raleway = Raleway({
  subsets: ["latin"],
  variable: "--font-raleway",
  display: "swap",
});
export const metadata: Metadata = {
  title: "Growing Up",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "bg-primary-bg-color transition-colors",
          raleway.variable,
        )}
      >
        <TranslationProvider>
          <ThemeProvider>{children}</ThemeProvider>
        </TranslationProvider>
      </body>
    </html>
  );
}
