import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import ThemeProvider from "@/providers/themeProvider";
import { cn } from "@/utils/tailwind";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const raleway = Raleway();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "bg-primary-bg-color transition-colors",
          raleway.className,
        )}
      >
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
