import type { Metadata } from "next";
import { Raleway } from "next/font/google";
// Providers
import ThemeProvider from "@/providers/themeProvider";
import { NextUIProvider } from "@nextui-org/system";
import TranslationProvider from "@/providers/translationProvider";

import "./globals.css";
import { cn } from "@/lib/utils";

const raleway = Raleway({
  subsets: ["latin"],
  variable: "--font-raleway",
  display: "swap",
});
export const metadata: Metadata = {
  title: "Growing Up",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("bg-primary-bg-color ", raleway.variable)}>
      <body>
        <NextUIProvider>
          <TranslationProvider>
            <ThemeProvider>{children}</ThemeProvider>
          </TranslationProvider>
        </NextUIProvider>
      </body>
    </html>
  );
}
